pool:
  name: default
  demands: Unity_2021.1.9f1

steps:
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Win64'
    unityEditorsPathMode: 'specify'
    customUnityEditorsPath: 'C:\_Projects\2021.1.9f1\Editor\Unity.exe'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'Eden'